apiVersion: v1
kind: Service
metadata:
  name: api-predict
  labels:
    app: api-predict
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
    protocol: TCP    
  selector:
    app: api-predict